version: "3.8"
services:
  spark-master:
    container_name: spark-master
    build: .
    ports:
      - "9000:8181"
      - "7077:7077"
    volumes:
      - ../../src/spark:/apps
      - ../../data:/data
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master
  spark-worker-a:
    container_name: spark-worker-a
    build: .
    ports:
      - "9001:8181"
      - "7000:7000"
    volumes:
      - ../../src/spark:/apps
      - ../../data:/data
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=4G
      - SPARK_DRIVER_MEMORY=4G
      - SPARK_EXECUTOR_MEMORY=4G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-a
  spark-worker-b:
    container_name: spark-worker-b
    build: .
    ports:
      - "9002:8181"
      - "7001:7000"
    volumes:
      - ../../src/spark:/apps
      - ../../data:/data
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=4G
      - SPARK_DRIVER_MEMORY=4G
      - SPARK_EXECUTOR_MEMORY=4G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-b
  demo-database:
    container_name: demo-database
    image: postgres:11.7-alpine
    ports: 
      - "5432:5432"
    environment: 
      - POSTGRES_PASSWORD=casa1234
networks:
  default:
    name: cluster_network
    external: true