version: "3.8"

services:
  hbase-master:
    build: .
    container_name: hbase-master
    hostname: hbase-master
    env_file:
      - ./hbase.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 datanode2:9864 datanode3:9864 zookeeper:2181"
    ports:
      - 16010:16010
  
  hbase-region:
    image: bde2020/hbase-regionserver:1.0.0-hbase1.2.6
    container_name: hbase-regionserver
    hostname: hbase-regionserver
    env_file:
      - ./hbase.env
    environment:
      HBASE_CONF_hbase_regionserver_hostname: hbase-region
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 datanode2:9864 datanode3:9864 zookeeper:2181 hbase-master:16010"
    ports:
      - 16030:16030

networks:
  default:
    name: cluster_network
    external: true