---
version: '3.8'
services:
  client-container:
    container_name: client-container
    build: .
    volumes:
      - ../../src/client:/apps
      - ../../data:/data
    command: tail -F anything
networks:
  default:
    name: cluster_network
    external: true