---
version: "3.8"
services:
  notebook:
    container_name: jupyter-container
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ../../src/client/data_processing:/home/jovyan/work
      - ./config/jupyter-config.json:/home/jovyan/.jupyter/jupyter_notebook_config.json
      - ./config:/home/jovyan/.jupyter/config
networks:
  default:
    name: cluster_network
    external: true